/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;
use serde_json::Value;

use super::{Error, configuration, urlencode};

pub struct RoomParticipationApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl RoomParticipationApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> RoomParticipationApiClient {
        RoomParticipationApiClient {
            configuration: configuration,
        }
    }
}

pub trait RoomParticipationApi {
    fn send_event_txnid(&self, room_id: &str, event_type: &str, txn_id: &str, body: Value) -> Result<::models::Model200SendEventTxnid, Error>;
}

impl RoomParticipationApi for RoomParticipationApiClient {
    fn send_event_txnid(&self, room_id: &str, event_type: &str, txn_id: &str, body: Value) -> Result<::models::Model200SendEventTxnid, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rooms/{roomId}/send/{eventType}/{txnId}", configuration.base_path, roomId=urlencode(room_id), eventType=urlencode(event_type), txnId=urlencode(txn_id));
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("access_token", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
