/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;
use serde_json::Value;

use super::{Error, configuration, urlencode};

pub struct RoomDirectoryApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl RoomDirectoryApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> RoomDirectoryApiClient {
        RoomDirectoryApiClient {
            configuration: configuration,
        }
    }
}

pub trait RoomDirectoryApi {
    fn delete_room_alias(&self, room_alias: &str) -> Result<Value, Error>;
    fn get_room_id_by_alias(&self, room_alias: &str) -> Result<::models::RoomDirRequestBody, Error>;
    fn set_room_alias(&self, room_alias: &str, room_id: ::models::RoomId) -> Result<Value, Error>;
}

impl RoomDirectoryApi for RoomDirectoryApiClient {
    fn delete_room_alias(&self, room_alias: &str) -> Result<Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/client/r0/directory/room/{roomAlias}", configuration.base_path, roomAlias=urlencode(room_alias));
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("access_token", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_room_id_by_alias(&self, room_alias: &str) -> Result<::models::RoomDirRequestBody, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/client/r0/directory/room/{roomAlias}", configuration.base_path, roomAlias=urlencode(room_alias));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn set_room_alias(&self, room_alias: &str, room_id: ::models::RoomId) -> Result<Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/client/r0/directory/room/{roomAlias}", configuration.base_path, roomAlias=urlencode(room_alias));
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("access_token", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.json(&room_id);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
