/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use serde_json::Value;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct SendToDeviceMessagingApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> SendToDeviceMessagingApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> SendToDeviceMessagingApiClient<C> {
        SendToDeviceMessagingApiClient {
            configuration: configuration,
        }
    }
}

pub trait SendToDeviceMessagingApi {
    fn send_to_device(&self, event_type: &str, txn_id: &str, body: ::models::Body) -> Box<Future<Item = Value, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>SendToDeviceMessagingApi for SendToDeviceMessagingApiClient<C> {
    fn send_to_device(&self, event_type: &str, txn_id: &str, body: ::models::Body) -> Box<Future<Item = Value, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Put, "/sendToDevice/{eventType}/{txnId}".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "access_token".to_owned(),
            }))
            .with_path_param("eventType".to_string(), event_type.to_string())
            .with_path_param("txnId".to_string(), txn_id.to_string())
            .with_body_param(body)
            .execute(self.configuration.borrow())
    }

}
