/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;
use serde_json::Value;

use super::{Error, configuration, urlencode};

pub struct SendToDeviceMessagingApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl SendToDeviceMessagingApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> SendToDeviceMessagingApiClient {
        SendToDeviceMessagingApiClient {
            configuration: configuration,
        }
    }
}

pub trait SendToDeviceMessagingApi {
    fn send_to_device(&self, event_type: &str, txn_id: &str, request_body: ::std::collections::HashMap<String, ::std::collections::HashMap<String, ::models::EventContent>>) -> Result<Value, Error>;
}

impl SendToDeviceMessagingApi for SendToDeviceMessagingApiClient {
    fn send_to_device(&self, event_type: &str, txn_id: &str, request_body: ::std::collections::HashMap<String, ::std::collections::HashMap<String, ::models::EventContent>>) -> Result<Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/sendToDevice/{eventType}/{txnId}", configuration.base_path, eventType=urlencode(event_type), txnId=urlencode(txn_id));
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("access_token", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
