[package]
name = "samples"
version = "0.1.0"
authors = ["Vamshik Shetty <vamshikdshetty@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "~0.11"
futures = "0.1.23"
tokio-core = "*"

[dependencies.matrix]
path = "../matrix"