/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct EndToEndEncryptionApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> EndToEndEncryptionApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> EndToEndEncryptionApiClient<C> {
        EndToEndEncryptionApiClient {
            configuration: configuration,
        }
    }
}

pub trait EndToEndEncryptionApi {
    fn query_keys(&self, query_keys: ::models::QueryKeys) -> Box<Future<Item = ::models::Model200QueryKeys, Error = Error<serde_json::Value>>>;
    fn upload_keys(&self, keys_upload: ::models::KeysUpload) -> Box<Future<Item = ::models::Model200KeysUpload, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>EndToEndEncryptionApi for EndToEndEncryptionApiClient<C> {
    fn query_keys(&self, query_keys: ::models::QueryKeys) -> Box<Future<Item = ::models::Model200QueryKeys, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/keys/query".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "access_token".to_owned(),
            }))
            .with_body_param(query_keys)
            .execute(self.configuration.borrow())
    }

    fn upload_keys(&self, keys_upload: ::models::KeysUpload) -> Box<Future<Item = ::models::Model200KeysUpload, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/keys/upload".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "access_token".to_owned(),
            }))
            .with_body_param(keys_upload)
            .execute(self.configuration.borrow())
    }

}
