/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Body {
    /// The messages to send. A map from user ID, to a map from device ID to message body. The device ID may also be `*`, meaning all known devices for the user.
    #[serde(rename = "messages",skip_serializing_if="Option::is_none")]
    pub messages: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, Value>>>,
}

impl Body {
    pub fn new() -> Body {
        Body {
            messages: None,
        }
    }
}
