/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ClaimKeysRequestBody {
    /// The keys to be claimed. A map from user ID, to a map from device ID to algorithm name.
    #[serde(rename = "one_time_keys")]
    pub one_time_keys: ::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>,
    /// The time (in milliseconds) to wait when downloading keys from remote servers. 10 seconds is the recommended default.
    #[serde(rename = "timeout",skip_serializing_if="Option::is_none")]
    pub timeout: Option<i32>,
}

impl ClaimKeysRequestBody {
    pub fn new(one_time_keys: ::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>) -> ClaimKeysRequestBody {
        ClaimKeysRequestBody {
            one_time_keys: one_time_keys,
            timeout: None,
        }
    }
}
