/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateRoom {
    /// Extra keys, such as ``m.federate``, to be added to the content of the `m.room.create`_ event. The server will clobber the following keys: ``creator``, ``room_version``. Future versions of the specification may allow the server to clobber other keys.
    #[serde(rename = "creation_content",skip_serializing_if="Option::is_none")]
    pub creation_content: Option<Value>,
    /// A list of state events to set in the new room. This allows the user to override the default state events set in the new room. The expected format of the state events are an object with type, state_key and content keys set.  Takes precedence over events set by ``preset``, but gets overriden by ``name`` and ``topic`` keys.
    #[serde(rename = "initial_state",skip_serializing_if="Option::is_none")]
    pub initial_state: Option<Vec<::models::CreateRoomStateEvent>>,
    /// A list of user IDs to invite to the room. This will tell the server to invite everyone in the list to the newly created room.
    #[serde(rename = "invite",skip_serializing_if="Option::is_none")]
    pub invite: Option<Vec<String>>,
    /// A list of objects representing third party IDs to invite into the room.
    #[serde(rename = "invite_3pid",skip_serializing_if="Option::is_none")]
    pub invite_3pid: Option<Vec<::models::Invite3pid>>,
    /// This flag makes the server set the ``is_direct`` flag on the ``m.room.member`` events sent to the users in ``invite`` and ``invite_3pid``. See `Direct Messaging`_ for more information.
    #[serde(rename = "is_direct",skip_serializing_if="Option::is_none")]
    pub is_direct: Option<bool>,
    /// If this is included, an ``m.room.name`` event will be sent into the room to indicate the name of the room. See Room Events for more information on ``m.room.name``.
    #[serde(rename = "name",skip_serializing_if="Option::is_none")]
    pub name: Option<String>,
    /// The power level content to override in the default power level event. This object is applied on top of the generated `m.room.power_levels`_ event content prior to it being sent to the room. Defaults to overriding nothing.
    #[serde(rename = "power_level_content_override",skip_serializing_if="Option::is_none")]
    pub power_level_content_override: Option<Value>,
    /// Convenience parameter for setting various default state events based on a preset.  If unspecified, the server should use the ``visibility`` to determine which preset to use. A visbility of ``public`` equates to a preset of ``public_chat`` and ``private`` visibility equates to a preset of ``private_chat``.
    #[serde(rename = "preset",skip_serializing_if="Option::is_none")]
    pub preset: Option<String>,
    /// The desired room alias **local part**. If this is included, a room alias will be created and mapped to the newly created room. The alias will belong on the *same* homeserver which created the room. For example, if this was set to \"foo\" and sent to the homeserver \"example.com\" the complete room alias would be ``#foo:example.com``.  The complete room alias will become the canonical alias for the room.
    #[serde(rename = "room_alias_name",skip_serializing_if="Option::is_none")]
    pub room_alias_name: Option<String>,
    /// The room version to set for the room. If not provided, the homeserver is to use its configured default. If provided, the homeserver will return a 400 error with the errcode ``M_UNSUPPORTED_ROOM_VERSION`` if it does not support the room version.
    #[serde(rename = "room_version",skip_serializing_if="Option::is_none")]
    pub room_version: Option<String>,
    /// If this is included, an ``m.room.topic`` event will be sent into the room to indicate the topic for the room. See Room Events for more information on ``m.room.topic``.
    #[serde(rename = "topic",skip_serializing_if="Option::is_none")]
    pub topic: Option<String>,
    /// A ``public`` visibility indicates that the room will be shown in the published room list. A ``private`` visibility will hide the room from the published room list. Rooms default to ``private`` visibility if this key is not included. NB: This should not be confused with ``join_rules`` which also uses the word ``public``.
    #[serde(rename = "visibility",skip_serializing_if="Option::is_none")]
    pub visibility: Option<String>,
}

impl CreateRoom {
    pub fn new() -> CreateRoom {
        CreateRoom {
            creation_content: None,
            initial_state: None,
            invite: None,
            invite_3pid: None,
            is_direct: None,
            name: None,
            power_level_content_override: None,
            preset: None,
            room_alias_name: None,
            room_version: None,
            topic: None,
            visibility: None,
        }
    }
}
