/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateRoomStateEvent {
    /// The state_key of the state event. Defaults to an empty string.
    #[serde(rename = "state_key",skip_serializing_if="Option::is_none")]
    pub state_key: Option<String>,
    /// The type of event to send.
    #[serde(rename = "type")]
    pub _type: String,
    /// The content of the event.
    #[serde(rename = "content")]
    pub content: Value,
}

impl CreateRoomStateEvent {
    pub fn new(_type: String, content: Value) -> CreateRoomStateEvent {
        CreateRoomStateEvent {
            state_key: None,
            _type: _type,
            content: content,
        }
    }
}
