/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeleteDevicesRequestBody {
    /// Additional authentication information for the user-interactive authentication API.
    #[serde(rename = "auth",skip_serializing_if="Option::is_none")]
    pub auth: Option<::std::collections::HashMap<String, Value>>,
    /// The list of device IDs to delete.
    #[serde(rename = "devices")]
    pub devices: Vec<String>,
}

impl DeleteDevicesRequestBody {
    pub fn new(devices: Vec<String>) -> DeleteDevicesRequestBody {
        DeleteDevicesRequestBody {
            auth: None,
            devices: devices,
        }
    }
}
