/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeviceLists : Information on end-to-end device updates, as specified in |device_lists_sync|.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceLists {
    #[serde(rename = "changed",skip_serializing_if="Option::is_none")]
    pub changed: Option<Vec<String>>,
    #[serde(rename = "left",skip_serializing_if="Option::is_none")]
    pub left: Option<Vec<String>>,
}

impl DeviceLists {
    /// Information on end-to-end device updates, as specified in |device_lists_sync|.
    pub fn new() -> DeviceLists {
        DeviceLists {
            changed: None,
            left: None,
        }
    }
}
