/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceDeleteReq {
    /// Additional authentication information for the user-interactive authentication API.
    #[serde(rename = "auth",skip_serializing_if="Option::is_none")]
    pub auth: Option<::std::collections::HashMap<String, Value>>,
}

impl DeviceDeleteReq {
    pub fn new() -> DeviceDeleteReq {
        DeviceDeleteReq {
            auth: None,
        }
    }
}
