/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Device : A client device

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Device {
    /// Identifier of this device.
    #[serde(rename = "device_id")]
    pub device_id: String,
    /// Display name set by the user for this device. Absent if no name has been set.
    #[serde(rename = "display_name",skip_serializing_if="Option::is_none")]
    pub display_name: Option<String>,
    /// The IP address where this device was last seen. (May be a few minutes out of date, for efficiency reasons).
    #[serde(rename = "last_seen_ip",skip_serializing_if="Option::is_none")]
    pub last_seen_ip: Option<String>,
    /// The timestamp (in milliseconds since the unix epoch) when this devices was last seen. (May be a few minutes out of date, for efficiency reasons).
    #[serde(rename = "last_seen_ts",skip_serializing_if="Option::is_none")]
    pub last_seen_ts: Option<i64>,
}

impl Device {
    /// A client device
    pub fn new(device_id: String) -> Device {
        Device {
            device_id: device_id,
            display_name: None,
            last_seen_ip: None,
            last_seen_ts: None,
        }
    }
}
