/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Event {
    /// Fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.
    #[serde(rename = "content",skip_serializing_if="Option::is_none")]
    pub content: Option<Value>,
    /// The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. `com.example.subdomain.event.type`
    #[serde(rename = "type",skip_serializing_if="Option::is_none")]
    pub _type: Option<String>,
}

impl Event {
    pub fn new() -> Event {
        Event {
            content: None,
            _type: None,
        }
    }
}
