/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Invite {
    /// A name which can be displayed to represent the user instead of their third party identifier
    #[serde(rename = "display_name",skip_serializing_if="Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "signed",skip_serializing_if="Option::is_none")]
    pub signed: Option<::models::Signed>,
}

impl Invite {
    pub fn new() -> Invite {
        Invite {
            display_name: None,
            signed: None,
        }
    }
}
