/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InviteState {
    /// array of StrippedState
    #[serde(rename = "events",skip_serializing_if="Option::is_none")]
    pub events: Option<Vec<::models::StrippedState>>,
}

impl InviteState {
    pub fn new() -> InviteState {
        InviteState {
            events: None,
        }
    }
}
