/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JoinRoomidReq {
    #[serde(rename = "third_party_signed",skip_serializing_if="Option::is_none")]
    pub third_party_signed: Option<::models::ThirdPartySigned>,
}

impl JoinRoomidReq {
    pub fn new() -> JoinRoomidReq {
        JoinRoomidReq {
            third_party_signed: None,
        }
    }
}
