/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JoinSigned {
    /// The Matrix ID of the invitee.
    #[serde(rename = "mxid")]
    pub mxid: String,
    /// The Matrix ID of the user who issued the invite.
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "signatures")]
    pub signatures: ::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>,
    /// The state key of the m.third_party_invite event.
    #[serde(rename = "token")]
    pub token: String,
}

impl JoinSigned {
    pub fn new(mxid: String, sender: String, signatures: ::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>, token: String) -> JoinSigned {
        JoinSigned {
            mxid: mxid,
            sender: sender,
            signatures: signatures,
            token: token,
        }
    }
}
