/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KeysUploadDeviceKeys : Identity keys for the device. May be absent if no new identity keys are required.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct KeysUploadDeviceKeys {
    #[serde(rename = "user_id",skip_serializing_if="Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "device_id",skip_serializing_if="Option::is_none")]
    pub device_id: Option<String>,
    #[serde(rename = "algorithms",skip_serializing_if="Option::is_none")]
    pub algorithms: Option<Vec<String>>,
    #[serde(rename = "keys",skip_serializing_if="Option::is_none")]
    pub keys: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "signatures",skip_serializing_if="Option::is_none")]
    pub signatures: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
}

impl KeysUploadDeviceKeys {
    /// Identity keys for the device. May be absent if no new identity keys are required.
    pub fn new() -> KeysUploadDeviceKeys {
        KeysUploadDeviceKeys {
            user_id: None,
            device_id: None,
            algorithms: None,
            keys: None,
            signatures: None,
        }
    }
}
