/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ListOfDevice {
    /// A list of all registered devices for this user.
    #[serde(rename = "devices",skip_serializing_if="Option::is_none")]
    pub devices: Option<Vec<::models::Device>>,
}

impl ListOfDevice {
    pub fn new() -> ListOfDevice {
        ListOfDevice {
            devices: None,
        }
    }
}
