/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListOfEvent : List of events.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ListOfEvent {
    /// The timeline of messages and state changes in the room.
    #[serde(rename = "events",skip_serializing_if="Option::is_none")]
    pub events: Option<Vec<::models::Event>>,
}

impl ListOfEvent {
    /// List of events.
    pub fn new() -> ListOfEvent {
        ListOfEvent {
            events: None,
        }
    }
}
