/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Model200LoginGet {
    /// The homeserver's supported login types
    #[serde(rename = "flows",skip_serializing_if="Option::is_none")]
    pub flows: Option<Vec<::models::LoginFlow>>,
}

impl Model200LoginGet {
    pub fn new() -> Model200LoginGet {
        Model200LoginGet {
            flows: None,
        }
    }
}
