/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Model200MediaUpload {
    /// The MXC URI to the uploaded content.
    #[serde(rename = "content_uri")]
    pub content_uri: String,
}

impl Model200MediaUpload {
    pub fn new(content_uri: String) -> Model200MediaUpload {
        Model200MediaUpload {
            content_uri: content_uri,
        }
    }
}
