/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RoomDirRequestBody {
    /// The room ID for this room alias.
    #[serde(rename = "room_id",skip_serializing_if="Option::is_none")]
    pub room_id: Option<String>,
    /// A list of servers that are aware of this room alias.
    #[serde(rename = "servers",skip_serializing_if="Option::is_none")]
    pub servers: Option<Vec<String>>,
}

impl RoomDirRequestBody {
    pub fn new() -> RoomDirRequestBody {
        RoomDirRequestBody {
            room_id: None,
            servers: None,
        }
    }
}
