/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoomidMessages : A list of messages with a new token to request more.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RoomidMessages {
    /// The token the pagination starts from. If ``dir=b`` this will be the token supplied in ``from``.
    #[serde(rename = "start",skip_serializing_if="Option::is_none")]
    pub start: Option<String>,
    /// A list of room events.
    #[serde(rename = "chunk",skip_serializing_if="Option::is_none")]
    pub chunk: Option<Vec<::models::MessagesRoomevent>>,
    /// The token the pagination ends at. If ``dir=b`` this token should be used again to request even earlier events.
    #[serde(rename = "end",skip_serializing_if="Option::is_none")]
    pub end: Option<String>,
}

impl RoomidMessages {
    /// A list of messages with a new token to request more.
    pub fn new() -> RoomidMessages {
        RoomidMessages {
            start: None,
            chunk: None,
            end: None,
        }
    }
}
