/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SetRoomStateWithKeyReq {
    #[serde(rename = "avatar_url",skip_serializing_if="Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(rename = "displayname",skip_serializing_if="Option::is_none")]
    pub displayname: Option<String>,
    #[serde(rename = "membership",skip_serializing_if="Option::is_none")]
    pub membership: Option<String>,
}

impl SetRoomStateWithKeyReq {
    pub fn new() -> SetRoomStateWithKeyReq {
        SetRoomStateWithKeyReq {
            avatar_url: None,
            displayname: None,
            membership: None,
        }
    }
}
