/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SyncPresence : The updates to the presence status of other users.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncPresence {
    #[serde(rename = "events",skip_serializing_if="Option::is_none")]
    pub events: Option<::models::ListOfEvent>,
}

impl SyncPresence {
    /// The updates to the presence status of other users.
    pub fn new() -> SyncPresence {
        SyncPresence {
            events: None,
        }
    }
}
