/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncRoomsStateEvents {
    /// Fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.
    #[serde(rename = "content",skip_serializing_if="Option::is_none")]
    pub content: Option<Value>,
    /// The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. `com.example.subdomain.event.type`
    #[serde(rename = "type",skip_serializing_if="Option::is_none")]
    pub _type: Option<String>,
    /// The globally unique event identifier.
    #[serde(rename = "event_id",skip_serializing_if="Option::is_none")]
    pub event_id: Option<String>,
    /// Contains the fully-qualified ID of the user who sent this event.
    #[serde(rename = "sender",skip_serializing_if="Option::is_none")]
    pub sender: Option<String>,
    /// Timestamp in milliseconds on originating homeserver when this event was sent.
    #[serde(rename = "origin_server_ts",skip_serializing_if="Option::is_none")]
    pub origin_server_ts: Option<i32>,
    /// A unique key which defines the overwriting semantics for this piece of room state. This value is often a zero-length string. The presence of this key makes this event a State Event. State keys starting with an @ are reserved for referencing user IDs, such as room members. With the exception of a few events, state events set with a given user's ID as the state key MUST only be set by that user.
    #[serde(rename = "state_key",skip_serializing_if="Option::is_none")]
    pub state_key: Option<String>,
    #[serde(rename = "unsigned",skip_serializing_if="Option::is_none")]
    pub unsigned: Option<::models::UnsignedData>,
    /// Optional. The previous content for this event. If there is no previous content, this key will be missing.
    #[serde(rename = "prev_content",skip_serializing_if="Option::is_none")]
    pub prev_content: Option<Value>,
}

impl SyncRoomsStateEvents {
    pub fn new() -> SyncRoomsStateEvents {
        SyncRoomsStateEvents {
            content: None,
            _type: None,
            event_id: None,
            sender: None,
            origin_server_ts: None,
            state_key: None,
            unsigned: None,
            prev_content: None,
        }
    }
}
