/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SyncAccountData : The private data that this user has attached to this room.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncAccountData {
    #[serde(rename = "events",skip_serializing_if="Option::is_none")]
    pub events: Option<::models::ListOfEvent>,
}

impl SyncAccountData {
    /// The private data that this user has attached to this room.
    pub fn new() -> SyncAccountData {
        SyncAccountData {
            events: None,
        }
    }
}
