/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SyncResponse : The initial snapshot or delta for the client to use to update their state.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SyncResponse {
    /// The batch token to supply in the ``since`` param of the next `/sync` request.
    #[serde(rename = "next_batch",skip_serializing_if="Option::is_none")]
    pub next_batch: Option<String>,
    #[serde(rename = "rooms",skip_serializing_if="Option::is_none")]
    pub rooms: Option<::models::SyncRooms>,
    #[serde(rename = "presence",skip_serializing_if="Option::is_none")]
    pub presence: Option<::models::ListOfEvent>,
    #[serde(rename = "account_data",skip_serializing_if="Option::is_none")]
    pub account_data: Option<::models::ListOfEvent>,
    /// Information on the send-to-device messages for the client device, as defined in |send_to_device_sync|.
    #[serde(rename = "to_device",skip_serializing_if="Option::is_none")]
    pub to_device: Option<Value>,
    #[serde(rename = "device_lists",skip_serializing_if="Option::is_none")]
    pub device_lists: Option<::models::DeviceLists>,
    #[serde(rename = "device_one_time_keys_count",skip_serializing_if="Option::is_none")]
    pub device_one_time_keys_count: Option<::std::collections::HashMap<String, i32>>,
}

impl SyncResponse {
    /// The initial snapshot or delta for the client to use to update their state.
    pub fn new() -> SyncResponse {
        SyncResponse {
            next_batch: None,
            rooms: None,
            presence: None,
            account_data: None,
            to_device: None,
            device_lists: None,
            device_one_time_keys_count: None,
        }
    }
}
