/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UnsignedData : Contains optional extra information about the event.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UnsignedData {
    /// The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
    #[serde(rename = "age",skip_serializing_if="Option::is_none")]
    pub age: Option<i32>,
    /// The client-supplied transaction ID, if the client being given the event is the same one which sent it.
    #[serde(rename = "transaction_id",skip_serializing_if="Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "redacted_because",skip_serializing_if="Option::is_none")]
    pub redacted_because: Option<::models::Event>,
}

impl UnsignedData {
    /// Contains optional extra information about the event.
    pub fn new() -> UnsignedData {
        UnsignedData {
            age: None,
            transaction_id: None,
            redacted_because: None,
        }
    }
}
