/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UserId {
    /// The fully qualified user ID of the invitee.
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl UserId {
    pub fn new(user_id: String) -> UserId {
        UserId {
            user_id: user_id,
        }
    }
}
