/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct KeysUpload {
    /// Identity keys for the device. May be absent if no new identity keys are required.
    #[serde(rename = "device_keys")]
    pub device_keys: Option<::models::DeviceKeys>,
    /// One-time public keys for `pre-key` messages. The names of the properties should be in the format `<algorithm>:<key_id>`. The format of the key is determined by the key algorithm. May be absent if no new one-time keys are required.
    #[serde(rename = "one_time_keys")]
    pub one_time_keys: Option<Value>,
}

impl KeysUpload {
    pub fn new() -> KeysUpload {
        KeysUpload {
            device_keys: None,
            one_time_keys: None,
        }
    }
}
