/*
 * Matrix Client-Server Registration and Login API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Model200QueryKeys {
    /// If any remote homeservers could not be reached, they are recorded here. The names of the properties are the names of the unreachable servers. If the homeserver could be reached, but the user or device was unknown, no failure is recorded. Instead, the corresponding user or device is missing from the `device_keys` result.
    #[serde(rename = "failures")]
    pub failures: Option<::std::collections::HashMap<String, Value>>,
    /// Information on the queried devices. A map from user ID, to a map from device ID to device information.  For each device, the information returned will be the same as uploaded via ``/keys/upload``, with the addition of an ``unsigned`` property.
    #[serde(rename = "device_keys")]
    pub device_keys: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, Value>>>,
}

impl Model200QueryKeys {
    pub fn new() -> Model200QueryKeys {
        Model200QueryKeys {
            failures: None,
            device_keys: None,
        }
    }
}
